import {DEFAULTS,makePlan,easier,swapAction,guidedReply,calendarEvent} from './planner.js';
const $=s=>document.querySelector(s);const KEY='daily-bro-v1';let checkin={...DEFAULTS},plan=makePlan(checkin),wins=[],rotation=0,calendarUrl='',scheduled=null;const icons={movement:'↗',connection:'✳',reset:'◌'};
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('visible');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('visible'),3500);}
function save(){try{localStorage.setItem(KEY,JSON.stringify({checkin,plan,wins}));}catch{toast('Browser storage is unavailable. Your plan still works in this tab.');}}
try{const s=JSON.parse(localStorage.getItem(KEY)||'null');if(s&&['daily','gym'].includes(s.checkin?.mode)&&Array.isArray(s.plan)&&s.plan.length===3&&s.plan.every(a=>typeof a.title==='string'&&typeof a.body==='string'&&typeof a.easyBody==='string'&&Number.isFinite(a.duration)&&['movement','connection','reset'].includes(a.category))){checkin={...DEFAULTS,...s.checkin};plan=s.plan;wins=Array.isArray(s.wins)?s.wins.filter(w=>typeof w.title==='string'&&typeof w.completed==='string').slice(0,100):[];}}catch{}
function element(tag,cls,text){const el=document.createElement(tag);if(cls)el.className=cls;if(text!==undefined)el.textContent=text;return el;}
function button(text,cls,handler){const b=element('button',cls,text);b.type='button';b.addEventListener('click',handler);return b;}
function render(){
 $('#actions').replaceChildren();plan.forEach((a,i)=>{const card=element('article',`action-card ${a.category}`),top=element('div','card-top');top.append(element('span','category',a.category.toUpperCase()),element('span','duration',`${a.duration} min`));card.append(top,element('div','card-icon',icons[a.category]),element('h3','',a.title),element('p','',a.body),element('p','card-reason',a.reason));const controls=element('div','card-tools');const easy=button(a.easy?'Already small':'Make it easier','text-button',()=>{plan[i]=easier(a);save();render();toast('A smaller step. Same intention.');});easy.disabled=a.easy||a.done;const swap=button('Swap','text-button',()=>{plan[i]=swapAction(a,checkin,plan);save();render();toast('A different idea, within your time.');});swap.disabled=a.done;controls.append(easy,swap,button('Schedule','text-button',()=>schedule(a)));const done=button(a.done?'✓ Done. That counts.':'○ I did this','done-button'+(a.done?' complete':''),()=>{a.done=!a.done;if(a.done){const entry={id:crypto.randomUUID(),title:a.title,mode:checkin.mode,completed:new Date().toISOString()};a.winId=entry.id;wins.unshift(entry);wins=wins.slice(0,100);toast('That counts. Nice making a little room for yourself.');}else{wins=wins.filter(w=>w.id!==a.winId);delete a.winId;}save();render();});done.setAttribute('aria-pressed',String(!!a.done));card.append(controls,done);$('#actions').append(card);});
 $('#plan-total').textContent=`${plan.reduce((n,a)=>n+a.duration,0)} minutes planned · ${plan.filter(a=>a.done).length} of 3 completed`;
 $('#win-count').textContent=wins.length;$('#daily-mode').classList.toggle('selected',checkin.mode==='daily');$('#gym-mode').classList.toggle('selected',checkin.mode==='gym');$('#daily-mode').setAttribute('aria-pressed',String(checkin.mode==='daily'));$('#gym-mode').setAttribute('aria-pressed',String(checkin.mode==='gym'));$('#setting-label').hidden=checkin.mode==='gym';$('#equipment-label').hidden=checkin.mode!=='gym';$('#mode-caption').textContent=checkin.mode==='gym'?'Movement at your pace. Recovery without guilt.':'A little movement. A little connection. A little breathing room.';
 $('#plan-heading').textContent=checkin.mode==='gym'?'A little movement. A little recovery.':'Your next three small steps.';$('#plan-note').textContent=checkin.energy==='low'?'Low energy noted. Your steps start small, and rest is a valid choice.':'A starting point, not a scorecard. Pick what fits and change what doesn’t.';
 document.querySelectorAll('[data-energy]').forEach(b=>{b.classList.toggle('selected',b.dataset.energy===checkin.energy);b.setAttribute('aria-pressed',String(b.dataset.energy===checkin.energy));});$('#minutes').value=String(checkin.minutes);$('#setting').value=checkin.setting;$('#equipment').value=checkin.equipment;renderWins();
}
function renderWins(){const root=$('#wins-list');root.replaceChildren();if(!wins.length){root.append(element('p','empty-wins','Your first little win is waiting. Complete any action on Your day and it will appear here.'));return;}wins.forEach(w=>{const row=element('div','win-row'),content=element('div');content.append(element('h3','',w.title),element('p','',`${new Date(w.completed).toLocaleDateString(undefined,{month:'short',day:'numeric'})} · ${w.mode==='gym'?'Gym Bro':'Daily Bro'}`));row.append(element('span','tick','✓'),content,button('Undo','text-button',()=>{wins=wins.filter(v=>v.id!==w.id);plan.forEach(a=>{if(a.winId===w.id){a.done=false;delete a.winId;}});save();render();}));root.append(row);});}
function view(name){$('#today-view').hidden=name!=='today';$('#wins-view').hidden=name!=='wins';document.querySelectorAll('.nav[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===name));window.scrollTo({top:0,behavior:'smooth'});}
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>view(b.dataset.view)));
document.querySelectorAll('dialog .close').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}}));
[['about-open','info-dialog'],['privacy-open','privacy-dialog'],['reset-open','reset-dialog']].forEach(([b,d])=>$('#'+b).addEventListener('click',()=>$('#'+d).showModal()));
document.querySelectorAll('[data-energy]').forEach(b=>b.addEventListener('click',()=>{checkin.energy=b.dataset.energy;document.querySelectorAll('[data-energy]').forEach(x=>{x.classList.toggle('selected',x===b);x.setAttribute('aria-pressed',String(x===b));});}));
function readCheckin(){checkin.minutes=Number($('#minutes').value);checkin.setting=$('#setting').value;checkin.equipment=$('#equipment').value;}
function build(){readCheckin();plan=makePlan(checkin,$('#context').value,rotation++);save();render();toast('Your new small steps are ready below.');$('#plan-heading').scrollIntoView({behavior:'smooth',block:'center'});}
$('#checkin-form').addEventListener('submit',e=>{e.preventDefault();build();});['daily','gym'].forEach(mode=>$('#'+mode+'-mode').addEventListener('click',()=>{if(checkin.mode===mode)return;readCheckin();checkin.mode=mode;rotation=0;plan=makePlan(checkin,$('#context').value,rotation);save();render();}));
function chat(role,text){const b=element('div','chat-bubble '+role);b.append(element('small','',role==='user'?'YOU':`${checkin.mode==='gym'?'GYM':'DAILY'} BRO · GUIDED DEMO`),element('span','',text));$('#chat-log').append(b);while($('#chat-log').children.length>20)$('#chat-log').firstElementChild.remove();$('#chat-log').scrollTop=$('#chat-log').scrollHeight;}
$('#chat-form').addEventListener('submit',e=>{e.preventDefault();const text=$('#chat-input').value.trim();if(!text)return;chat('user',text);$('#chat-input').value='';chat('assistant',guidedReply(text,checkin,plan));});
function schedule(a){scheduled=a;$('#schedule-title').textContent=a.title;const date=new Date(Date.now()+3600000);date.setMinutes(0,0,0);const local=new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,16);$('#schedule-time').value=local;$('#calendar-link').hidden=true;$('#schedule-dialog').showModal();}
$('#schedule-form').addEventListener('submit',e=>{e.preventDefault();try{const start=new Date($('#schedule-time').value);if(start.getTime()<Date.now()){toast('Choose a time in the future.');return;}if(calendarUrl)URL.revokeObjectURL(calendarUrl);calendarUrl=URL.createObjectURL(new Blob([calendarEvent(scheduled,start)],{type:'text/calendar;charset=utf-8'}));const a=$('#calendar-link');a.href=calendarUrl;a.download='daily-bro-reminder.ics';a.hidden=false;}catch(error){toast(error.message);}});
$('#reset-confirm').addEventListener('click',()=>{try{localStorage.removeItem(KEY);}catch{}checkin={...DEFAULTS};rotation=0;plan=makePlan(checkin);wins=[];$('#context').value='';$('#chat-log').replaceChildren();$('#reset-dialog').close();render();view('today');toast('A fresh start. No catching up required.');});
$('#today-date').textContent=new Date().toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'}).toUpperCase();render();
