export const DEFAULTS={mode:'daily',energy:'okay',minutes:20,setting:'campus',equipment:'none'};
const action=(id,category,title,body,duration,easyTitle,easyBody)=>({id,category,title,body,duration,easyTitle,easyBody});
export const library={
movement:[action('walk','movement','Take the scenic route.','Step away from your screen for a comfortable walk or roll. Leave the headphones off for a minute and notice your surroundings.',8,'Change your view.','Spend two minutes by a window or outside, seated or standing. You do not need to go far.'),action('loosen','movement','Unfold from your desk.','Take a few minutes of comfortable movement: loosen your hands and shoulders, change position, or walk around your room. Stay within a pain-free range.',5,'Unclench. Exhale.','Relax your hands and shoulders and change position for one minute.'),action('music','movement','Move to one good song.','Put on a favorite song. Move however feels good: seated, standing, or a gentle walk. This is a break, not a workout test.',4,'Press play.','Listen to one minute of a favorite song. Moving is optional.')],
connection:[action('club','connection','Find your kind of people.','Open your campus club directory. Choose one club you are curious about and check its next meeting. Save the real date before making plans.',7,'Just find one club.','Spend two minutes finding a club name that interests you. You can decide about attending later.'),action('friend','connection','Send the first hello.','Message someone you already know: “Hey, I thought of you today. How have you been?” No perfect wording and no pressure for an instant reply.',3,'Send a small hello.','Send a quick “Thinking of you—hope your day is going okay” to someone you know.'),action('kind','connection','Notice something good.','If a natural moment comes up, offer a sincere compliment about someone’s effort or choice: “Your explanation really helped me.” Let them choose whether to keep talking.',3,'Make room for kindness.','Think of someone whose effort you appreciate. Write one sentence you could tell them later.'),action('smile','connection','Make a small connection.','If someone seems open to it, give a friendly hello or smile. Keep it light, respect their space, and move on if they do not engage.',2,'Reconnect with someone familiar.','Send a friendly emoji or hello to someone you already know.')],
reset:[action('shutdown','reset','Give work a finish line.','Write down your next work step, close the extra tabs, and put your screen aside for a few minutes. You can return without carrying it all in your head.',5,'Close one loop.','Write down the next thing you will do when you return, then look away from the screen for a minute.'),action('pause','reset','Have a moment with no goal.','Sit somewhere comfortable. Look out a window, sip a drink, or simply rest. You do not have to make this time useful.',5,'Take one quiet minute.','Put your phone face down for one minute. Let this be a pause with no task attached.'),action('joy','reset','Do a tiny thing you like.','Read a few pages, sketch something silly, or listen to a favorite song. Choose enjoyment over achievement for a few minutes.',6,'Choose a small pleasure.','Play a minute of a song you like or look at a favorite photo.')],
gym:[action('gym-walk','movement','Make showing up enough.','Take an easy walk, roll, or comfortable movement break. If you are at the gym, choose a familiar, easy activity. You should feel free to stop early.',10,'Start with two minutes.','Try two minutes of comfortable movement. Decide afterward whether you want more.'),action('gym-session','movement','Keep the session familiar.','Use comfortable movements you already know. Start easy, take breaks, and finish before you feel drained. If equipment is unfamiliar, ask gym staff to show you.',20,'Keep it light.','Take a short, easy movement break instead of a full session. No need to push today.'),action('gym-prepare','movement','Lower the starting barrier.','Set out your shoes and water, choose a familiar activity, and pick a realistic time. Planning counts today; the session can happen when you have room.',5,'Put out your shoes.','Set out one thing that makes your next movement break easier.')],
recovery:[action('recover','reset','Leave room to recover.','After moving, slow down and take a comfortable seated break. Notice how you feel. Rest is part of looking after yourself.',5,'Sit. Breathe. Reset.','Take a quiet minute in a comfortable position.'),action('gym-boundary','reset','Skip the comparison.','Choose one thing to appreciate about showing up, regardless of distance, weight, or appearance. Write it down and let the session be enough.',3,'Count showing up.','Write: “I made a little room for myself today.”')]
};
export function makePlan(checkin,context='',rotation=0){
 const c={...DEFAULTS,...checkin};const text=context.toLowerCase();const budget=[10,20,45,60].includes(Number(c.minutes))?Number(c.minutes):20;const low=c.energy==='low';
 let move=c.mode==='gym'?library.gym[(low||budget===10)?0:c.equipment==='gym'?1:0]:library.movement[(low?1:rotation)%3];
 let people=c.setting==='campus'&&!low&&budget>=20?library.connection[0]:library.connection[1];
 if(/lonely|alone|friend|spoken|social/.test(text))people=library.connection[1];
 if(/club|campus/.test(text)&&budget>=20&&!low)people=library.connection[0];
 let rest=c.mode==='gym'?library.recovery[rotation%2]:library.reset[/work|study|studying|exam|deadline|overwhelm/.test(text)?0:rotation%3];
 if(rotation>0){people=library.connection[(rotation+(c.setting==='campus'?0:1))%4];if(c.setting!=='campus'&&people.id==='club')people=library.connection[1];}
 let list=[move,people,rest].map(x=>({...x,done:false,easy:false,reason:reason(x,c)}));
 if(low)list=list.map(easier);
 while(list.reduce((n,x)=>n+x.duration,0)>budget){const idx=list.findIndex(x=>!x.easy);if(idx<0)break;list[idx]=easier(list[idx]);}
 return list;
}
function reason(x,c){if(c.energy==='low')return 'You said your energy is low. Keep the starting point small.';if(x.id==='club')return 'You selected campus. This helps you find a real opportunity without inventing an event.';if(x.category==='movement')return c.mode==='gym'?'A manageable start, using activity that already feels familiar.':'A change of pace after time at a screen.';if(x.category==='connection')return 'Connection can start with one small, respectful gesture.';return 'Your day deserves a pause that is not another assignment.';}
export function easier(x){return {...x,title:x.easyTitle,body:x.easyBody,duration:Math.min(x.duration,2),easy:true,done:false};}
export function swapAction(x,c,used=[]){const pool=x.category==='movement'?(c.mode==='gym'?library.gym:library.movement):x.category==='connection'?library.connection:(c.mode==='gym'?library.recovery:library.reset);let next=pool[(pool.findIndex(v=>v.id===x.id)+1)%pool.length];if(next.id==='club'&&c.setting!=='campus')next=library.connection[1];const allowed=Number(c.minutes)-used.filter(a=>a!==x).reduce((n,a)=>n+a.duration,0);const item={...next,reason:reason(next,c),done:false,easy:false};return c.energy==='low'||item.duration>allowed?easier(item):item;}
export function guidedReply(text,c,plan){const t=text.toLowerCase();if(/pain|injur|chest|dizz|faint/.test(t))return 'Let’s pause the workout idea. I can’t assess symptoms or injuries. Choose rest and ask a qualified clinician about safe activity; if symptoms are severe or urgent, seek immediate medical help.';if(/suicid|kill myself|end my life|hurt myself/.test(t))return 'I’m sorry you’re feeling this much pain. Please reach out to someone you trust who can stay with you. If you might act on these thoughts, contact local emergency services or a crisis service now. This demo cannot provide crisis care.';if(/tired|overwhelm|exhaust|too much|easier/.test(t))return `Then let’s make the day smaller. Try just this: ${plan[2]?.easyBody||'Take one quiet minute away from your screen.'} Use “Make it easier” on any card. You can leave the other steps for another day.`;if(/gym|workout|exercise/.test(t))return 'Switch to Gym Bro and choose your energy, time, and equipment. Keep movement familiar and comfortable. Showing up for a small session is enough; you do not need to turn every visit into a personal record.';if(/club|friend|lonely|social|compliment|smile/.test(t))return 'Pick one low-pressure connection: message someone you know, or check a club’s real meeting details. If you compliment someone, make it sincere and about their effort or choice. A short exchange counts; they do not owe you a conversation.';if(/work|study|guilt|deadline|break/.test(t))return 'Write down your next work step so it has a place to wait. Then take the break on your plan. You can care about your goals and still make room for yourself today.';return `Start with “${plan[0]?.title||'Take one small step'}” if it fits. Or choose the card that feels easiest. These are guided demo replies; for a new plan, add a little context in the check-in above and press “Find my next small steps.”`;}
export function calendarEvent(action,start){const d=new Date(start);if(Number.isNaN(d.getTime()))throw Error('Choose a valid date and time.');const stamp=v=>v.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'');const escape=s=>String(s).replace(/\\/g,'\\\\').replace(/\r?\n/g,'\\n').replace(/,/g,'\\,').replace(/;/g,'\\;');return ['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Daily Bro//Small steps//EN','BEGIN:VEVENT',`UID:${crypto.randomUUID()}@daily-bro`,`DTSTAMP:${stamp(new Date())}`,`DTSTART:${stamp(d)}`,`DTEND:${stamp(new Date(d.getTime()+action.duration*60000))}`,`SUMMARY:${escape(action.title)}`,`DESCRIPTION:${escape(action.body+' Personal reminder only; no event booking.')}`,'END:VEVENT','END:VCALENDAR'].join('\r\n');}
